# Generated by Django 4.2.11 on 2024-06-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
