# Generated by Django 4.2.11 on 2024-06-21 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_course_instructor_alter_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ispublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrol', to=settings.AUTH_USER_MODEL),
        ),
    ]
