# Generated by Django 4.2.11 on 2024-06-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_ispublished_alter_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
