# Generated by Django 4.2.11 on 2024-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_module_created_at_alter_module_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.TextField(max_length=300),
        ),
    ]
