# Generated by Django 4.2.11 on 2024-06-27 11:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='cover-img.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='event/cover/'),
        ),
    ]
