# Generated by Django 4.2.11 on 2024-06-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_event_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='google_meet_link',
        ),
    ]
