# Generated by Django 4.2.11 on 2024-06-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_alter_participant_session_alter_participant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='coaching.event'),
        ),
    ]
