# Generated by Django 4.2.11 on 2024-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_remove_event_google_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='discount_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
