# Generated by Django 4.2.11 on 2024-07-04 20:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_thread_id_alter_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='post',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='post'),
        ),
    ]
