# Generated by Django 4.2.11 on 2025-04-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_category_options_thread_is_community_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='community.threadreply'),
        ),
    ]
