# Generated by Django 4.2.11 on 2024-07-04 21:19

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_thread_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='post',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='threadreply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.thread'),
        ),
    ]
