# Generated by Django 4.2.11 on 2024-07-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_thread_post_alter_threadreply_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
