# Generated by Django 4.2.11 on 2024-08-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at']},
        ),
    ]
