# Generated by Django 4.2.11 on 2024-08-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
